apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # Type of service (LoadBalancer for external access)
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80        # Port on which the service is exposed
    targetPort: 80  # Port on the container to forward traffic to
